import { buildMediaSlug } from "@/lib/slug";

export type MediaKind = "anime" | "movie";

export interface WatchProvider {
  name: string;
  logo: string | null;
}

export interface WatchProviders {
  region: string | null;
  link: string | null;
  flatrate: WatchProvider[];
  rent: WatchProvider[];
  buy: WatchProvider[];
}

export interface EndingExplainedFaqItem {
  q: string;
  a: string;
}

/** The structured content stored in movies/anime.ending_explained_content
 *  (jsonb), generated by crawler/ending-explained-generator.mjs. */
export interface EndingExplained {
  recap: string;
  ending: string;
  themes: string;
  faq: EndingExplainedFaqItem[];
}

export interface MediaItem {
  id: string;
  /** URL-safe, human-readable identifier, e.g. "the-matrix-1999-603". Always
   *  present — falls back to a slugified title+id when the DB row predates
   *  the slug column. This is also the /ending-explained/[slug] route param. */
  slug: string;
  kind: MediaKind;
  title: string;
  description: string;
  posterUrl?: string;
  year?: number;
  score?: number;
  /** Real count of people who rated this (TMDB vote_count / Jikan scored_by /
   *  AniList scoreDistribution sum / Kitsu ratingFrequencies sum). Only
   *  present when the source actually reports one — used to populate JSON-LD
   *  aggregateRating.ratingCount, which Google requires alongside ratingValue. */
  ratingCount?: number;
  genres: string[];
  source?: string;
  watchProviders?: WatchProviders | null;
  /** SEO/topical tags. Rendered as chips on the page and used to fight thin
   *  content + give Google more on-page topical signal. */
  tags?: string[];
  /** Cast/voice-cast, sourced from TMDB credits (movies) or Jikan characters
   *  (anime) — never AI-invented, since getting a real person's name wrong
   *  is worse than not showing a cast section at all. */
  castList?: { name: string; role: string; photoUrl?: string | null }[];
  /** True when an editor has pulled this page out of the sitemap + search
   *  index via /admin (thin/duplicate content). The page still renders
   *  normally for visitors and in the admin preview, just with a noindex
   *  robots meta tag. */
  noindex?: boolean;
  /** The Ending Explained write-up. A title has no public page at all until
   *  this is present — see getPublishedTitleBySlug(). */
  endingExplained?: EndingExplained;
  endingExplainedWordCount?: number;
  endingExplainedPublishedAt?: string;
  likes: number;
}

export function normalizeAnime(item: any): MediaItem {
  const title = item?.title ?? item?.titles?.[0]?.title ?? "Untitled anime";
  const synopsis = item?.synopsis ?? item?.background ?? "A compelling anime pick from the current catalog.";
  const genres = Array.isArray(item?.genres)
    ? item.genres.map((genre: any) => genre?.name ?? genre).filter(Boolean)
    : [];
  const id = String(item?.mal_id ?? item?.id ?? title);
  const year = item?.year ?? item?.aired?.prop?.from?.year;
  return {
    id,
    slug: buildMediaSlug(title, year, id),
    kind: "anime",
    title,
    description: synopsis.replace(/\s+/g, " ").trim().slice(0, 180),
    posterUrl: item?.images?.jpg?.image_url ?? item?.images?.webp?.image_url,
    year: item?.year ?? item?.aired?.prop?.from?.year,
    score: item?.score,
    ratingCount: typeof item?.scored_by === "number" ? item.scored_by : undefined,
    genres,
    source: "jikan",
    likes: 0,
  };
}

export function normalizeMovie(item: any): MediaItem {
  const title = item?.title ?? item?.name ?? "Untitled movie";
  const description = item?.overview ?? item?.tagline ?? "A notable movie pick from the current catalog.";
  const genres = Array.isArray(item?.genres)
    ? item.genres.map((genre: any) => genre?.name ?? genre).filter(Boolean)
    : [];
  const id = String(item?.id ?? title);
  const year = item?.release_date ? Number(item.release_date.slice(0, 4)) : item?.first_air_date ? Number(item.first_air_date.slice(0, 4)) : undefined;
  return {
    id,
    slug: buildMediaSlug(title, year, id),
    kind: "movie",
    title,
    description: description.replace(/\s+/g, " ").trim().slice(0, 180),
    posterUrl: item?.poster_path ? `https://image.tmdb.org/t/p/w500${item.poster_path}` : undefined,
    year,
    score: item?.vote_average,
    ratingCount: typeof item?.vote_count === "number" ? item.vote_count : undefined,
    genres,
    source: "tmdb",
    likes: 0,
  };
}
